services:
    whatsapp-web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: whatsapp-web-app
        restart: unless-stopped
        ports:
            - "4000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
            - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
        volumes:
            - ./sessions:/app/.wwebjs_auth
            - ./logs:/app/logs
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        external: true

volumes:
    sessions:
    logs:
